#!/usr/bin/env bash
set -euo pipefail

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
ip_dir=$(cd -- "$script_dir/.." && pwd)

mode=${1:---update}
case "$mode" in
    --update|--check) ;;
    *)
        echo "usage: $0 [--update|--check]" >&2
        exit 2
        ;;
esac

deps_root=${LITESD_DEPS_ROOT:-/tmp/cpustc-litesd-upstream.LdbX7h}
migen_dir=${MIGEN_SOURCE_DIR:-$deps_root/migen}
litex_dir=${LITEX_SOURCE_DIR:-$deps_root/litex}
litesdcard_dir=${LITESDCARD_SOURCE_DIR:-$deps_root/litesdcard}

check_revision() {
    local name=$1
    local source_dir=$2
    local expected=$3
    local actual

    if [[ ! -d "$source_dir/.git" ]]; then
        echo "$name source is not a Git checkout: $source_dir" >&2
        exit 1
    fi
    actual=$(git -C "$source_dir" rev-parse HEAD)
    if [[ "$actual" != "$expected" ]]; then
        echo "$name revision mismatch: expected $expected, got $actual" >&2
        exit 1
    fi
}

check_sha256() {
    local source_file=$1
    local expected=$2
    local actual

    actual=$(sha256sum "$source_file" | awk '{print $1}')
    if [[ "$actual" != "$expected" ]]; then
        echo "SHA-256 mismatch for $source_file: expected $expected, got $actual" >&2
        exit 1
    fi
}

check_revision Migen "$migen_dir" e19524c963a8342952840983047557707fbe0b6a
check_revision LiteX "$litex_dir" 37b75bd468e228b2c8637727c68a1320eb5531a4
check_revision LiteSDCard "$litesdcard_dir" 227d61bc2b92ca56cac78a539b98e378468b1ba1
check_sha256 "$ip_dir/../TensorCore/src/main/resources/verilog-axi/axi_dma_rd.v" \
    853ff3aedc44ec0c12ef3ae8b84d7559800d372f76832c7c133ed5eecac61dd8
check_sha256 "$ip_dir/../TensorCore/src/main/resources/verilog-axi/axi_dma_wr.v" \
    91b24115e3a5940a6057d06554fb5c61594a22fc71391e871e5c14f1e21ea0b2

build_dir=$(mktemp -d /tmp/cpustc-litesd-axi.XXXXXX)
cleanup() {
    case "$build_dir" in
        /tmp/cpustc-litesd-axi.*) rm -rf -- "$build_dir" ;;
    esac
}
trap cleanup EXIT

patched_litesdcard_dir="$build_dir/litesdcard"
cp -a -- "$litesdcard_dir" "$patched_litesdcard_dir"
git -C "$patched_litesdcard_dir" apply --unidiff-zero --whitespace=nowarn \
    "$ip_dir/patches/export_debug_signals.patch"

PYTHONHASHSEED=0 PYTHONPATH="$migen_dir:$litex_dir:$patched_litesdcard_dir" \
    python3 "$ip_dir/generator/gen_axi.py" --clk-freq 100e6 --output-dir "$build_dir"

generated_rtl="$build_dir/gateware/litesdcard_core.v"
generated_csr="$build_dir/csr.csv"
expected_device=xc7a200tfbg676-2

# LiteX embeds wall-clock time in the RTL header/trailer and CSR header.
# Normalize only those lines so fixed source revisions produce identical files.
sed -i -E 's|^// Date +:.*$|// Date       : normalized|' "$generated_rtl"
sed -i -E \
    's|^//  Auto-Generated by LiteX on .*[.]$|//  Auto-Generated by LiteX; timestamp normalized.|' \
    "$generated_rtl"
sed -i -E 's|^# Auto-generated by LiteX \(([^)]+)\) on .*$|# Auto-generated by LiteX (\1); timestamp normalized|' "$generated_csr"

if ! grep -Fqx "// Device     : $expected_device" "$generated_rtl"; then
    echo "generated RTL does not target $expected_device" >&2
    exit 1
fi

for primitive in IDDR FDCE; do
    if ! grep -Eq "^[[:space:]]*$primitive[[:space:]]" "$generated_rtl"; then
        echo "generated RTL is missing 7-series $primitive I/O primitives" >&2
        exit 1
    fi
done

diff -u \
    <(sed -n '/^csr_base,/p; /^csr_register,/p' "$ip_dir/csr.csv") \
    <(sed -n '/^csr_base,/p; /^csr_register,/p' "$generated_csr")

for port in \
    dma_wr_desc_addr dma_wr_desc_len dma_wr_desc_valid dma_wr_desc_ready \
    dma_wr_status_len dma_wr_status_error dma_wr_status_valid \
    dma_wr_data_tdata dma_wr_data_tkeep dma_wr_data_tvalid dma_wr_data_tready dma_wr_data_tlast \
    dma_rd_desc_addr dma_rd_desc_len dma_rd_desc_valid dma_rd_desc_ready \
    dma_rd_status_error dma_rd_status_valid \
    dma_rd_data_tdata dma_rd_data_tkeep dma_rd_data_tvalid dma_rd_data_tready dma_rd_data_tlast \
    dma_block2mem_enabled dma_mem2block_enabled mem2block_payload_requested \
    debug_crc_error_next debug_crc_error_latched debug_crc_sample_enable debug_sd_dat \
    debug_crc_count debug_datar_state debug_datar_count debug_block_index \
    debug_local_crc_dat0 debug_local_crc_dat1 debug_local_crc_dat2 debug_local_crc_dat3 \
    debug_frontend_offset_bytes debug_frontend_state \
    debug_crc_expected debug_crc_mismatch debug_crc_correct debug_data_done \
    debug_datar_valid debug_sample_ce debug_clocker_ce debug_clocker_clk \
    debug_clocker_clk_en debug_clocker_stop debug_datar_reset debug_sd_data_oe \
    debug_crc16_enable debug_crc16_reset debug_clock_divider debug_data_count \
    debug_datar_source_valid debug_datar_source_ready debug_datar_source_data \
    debug_core_state debug_dataw_state debug_cmdw_state debug_cmdr_state \
    debug_mem2block_fifo_level debug_cmd_index debug_data_type debug_cmd_send \
    debug_cmd_event debug_data_event debug_sd_cmd_i debug_sd_cmd_o debug_sd_cmd_oe \
    debug_dataw_sink_valid debug_dataw_sink_ready
do
    if ! grep -q "\b$port\b" "$generated_rtl"; then
        echo "generated RTL is missing port $port" >&2
        exit 1
    fi
done

if ! grep -Eq \
    '^[[:space:]]*assign[[:space:]]+mem2block_payload_requested[[:space:]]*=[[:space:]]*core_write_data_active[[:space:]]*;' \
    "$generated_rtl"; then
    echo "generated mem2block payload gate is not driven by the LiteSD write-data phase" >&2
    exit 1
fi

if grep -Eq \
    '^[[:space:]]*assign[[:space:]]+mem2block_payload_requested[[:space:]]*=.*(source|sink)_ready' \
    "$generated_rtl"; then
    echo "generated mem2block payload gate must not depend on stream ready" >&2
    exit 1
fi

if grep -q '\bwb_dma_' "$generated_rtl"; then
    echo "generated RTL still exposes the removed Wishbone DMA interface" >&2
    exit 1
fi

if [[ "$mode" == "--check" ]]; then
    cmp "$generated_rtl" "$ip_dir/rtl/litesdcard_core.v"
    cmp "$generated_csr" "$ip_dir/csr.csv"
else
    install -m 0644 "$generated_rtl" "$ip_dir/rtl/litesdcard_core.v"
    install -m 0644 "$generated_csr" "$ip_dir/csr.csv"
fi

sha256sum "$generated_rtl" "$generated_csr"
