#!/usr/bin/env python3
"""Generate the functional CPUSTCore-to-CPUSTC SoC SystemVerilog adapter."""

from __future__ import annotations

import argparse
import difflib
import os
import re
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Port:
    direction: str
    name: str


REQUIRED_CONNECTIONS = (
    ("clock", "input", "aclk"),
    ("reset", "input", "~aresetn"),
    ("io_hardwareInterrupt", "input", "intrpt"),
    ("io_axi_ar_valid", "output", "arvalid"),
    ("io_axi_ar_ready", "input", "arready"),
    ("io_axi_ar_addr", "output", "araddr"),
    ("io_axi_ar_len", "output", "cpu_arlen"),
    ("io_axi_ar_size", "output", "arsize"),
    ("io_axi_ar_burst", "output", "arburst"),
    ("io_axi_ar_id", "output", "arid"),
    ("io_axi_r_valid", "input", "rvalid"),
    ("io_axi_r_ready", "output", "rready"),
    ("io_axi_r_data", "input", "rdata"),
    ("io_axi_r_last", "input", "rlast"),
    ("io_axi_r_resp", "input", "rresp"),
    ("io_axi_r_id", "input", "rid"),
    ("io_axi_aw_valid", "output", "awvalid"),
    ("io_axi_aw_ready", "input", "awready"),
    ("io_axi_aw_addr", "output", "awaddr"),
    ("io_axi_aw_len", "output", "cpu_awlen"),
    ("io_axi_aw_size", "output", "awsize"),
    ("io_axi_aw_burst", "output", "awburst"),
    ("io_axi_aw_id", "output", "cpu_awid"),
    ("io_axi_w_valid", "output", "wvalid"),
    ("io_axi_w_ready", "input", "wready"),
    ("io_axi_w_data", "output", "wdata"),
    ("io_axi_w_strb", "output", "wstrb"),
    ("io_axi_w_last", "output", "wlast"),
    ("io_axi_b_valid", "input", "bvalid"),
    ("io_axi_b_ready", "output", "bready"),
    ("io_axi_b_resp", "input", "bresp"),
    ("io_axi_b_id", "input", "bid"),
)

# Optional CPUSTCore observation ports mapped to the legacy SoC debug boundary.
DEBUG_PORTS = {
    "io_retirePc": ("retire_pc", "[31:0]"),
    "io_cmt_0_valid": ("cmt0_valid", ""),
    "io_cmt_0_pc": ("cmt0_pc", "[31:0]"),
    "io_cmt_0_data": ("cmt0_data", "[31:0]"),
    "io_cmt_0_inst": ("cmt0_inst", "[31:0]"),
    "io_cmt_0_rd_valid": ("cmt0_rd_valid", ""),
    "io_cmt_0_rd": ("cmt0_rd", "[4:0]"),
}


ADAPTER_HEADER = """`default_nettype none

// Generated by scripts/gen_cpustcore_adapter.py. Do not edit manually.
module core_top (
    input  wire [7:0]  intrpt,
    input  wire        aclk,
    input  wire        aresetn,

    output wire [3:0]  arid,
    output wire [31:0] araddr,
    output wire [3:0]  arlen,
    output wire [2:0]  arsize,
    output wire [1:0]  arburst,
    output wire [1:0]  arlock,
    output wire [3:0]  arcache,
    output wire [2:0]  arprot,
    output wire        arvalid,
    input  wire        arready,
    input  wire [3:0]  rid,
    input  wire [31:0] rdata,
    input  wire [1:0]  rresp,
    input  wire        rlast,
    input  wire        rvalid,
    output wire        rready,

    output wire [3:0]  awid,
    output wire [31:0] awaddr,
    output wire [3:0]  awlen,
    output wire [2:0]  awsize,
    output wire [1:0]  awburst,
    output wire [1:0]  awlock,
    output wire [3:0]  awcache,
    output wire [2:0]  awprot,
    output wire        awvalid,
    input  wire        awready,
    output wire [3:0]  wid,
    output wire [31:0] wdata,
    output wire [3:0]  wstrb,
    output wire        wlast,
    output wire        wvalid,
    input  wire        wready,
    input  wire [3:0]  bid,
    input  wire [1:0]  bresp,
    input  wire        bvalid,
    output wire        bready,
    input  wire        break_point,
    input  wire        infor_flag,
    input  wire [4:0]  reg_num,
    output wire        ws_valid,
    output wire [31:0] rf_rdata,
    output wire [31:0] debug0_wb_pc,
    output wire [3:0]  debug0_wb_rf_wen,
    output wire [4:0]  debug0_wb_rf_wnum,
    output wire [31:0] debug0_wb_rf_wdata,
    output wire [31:0] debug0_wb_inst
);
"""


def strip_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    return re.sub(r"//[^\n]*", "", text)


def cpu_port_block(text: str) -> str:
    source = strip_comments(text)
    match = re.search(r"(?m)^\s*module\s+CPU\s*\(", source)
    if not match:
        raise ValueError("module CPU port list not found")

    start = source.find("(", match.start())
    depth = 0
    for index in range(start, len(source)):
        if source[index] == "(":
            depth += 1
        elif source[index] == ")":
            depth -= 1
            if depth == 0:
                return source[start + 1 : index]
    raise ValueError("unterminated module CPU port list")


def parse_cpu_ports(text: str) -> dict[str, Port]:
    ports: dict[str, Port] = {}
    direction: str | None = None
    for raw_item in cpu_port_block(text).split(","):
        item = " ".join(raw_item.split())
        if not item:
            continue
        direction_match = re.match(r"^(input|output|inout)\b(.*)$", item)
        if direction_match:
            direction = direction_match.group(1)
            item = direction_match.group(2).strip()
        if direction is None:
            raise ValueError(f"port declaration has no direction: {raw_item!r}")
        name_match = re.search(r"([A-Za-z_][A-Za-z0-9_$]*)$", item)
        if not name_match:
            raise ValueError(f"cannot parse port name: {raw_item!r}")
        name = name_match.group(1)
        if name in ports:
            raise ValueError(f"duplicate CPU port: {name}")
        ports[name] = Port(direction=direction, name=name)
    return ports


def validate_required_ports(ports: dict[str, Port]) -> None:
    errors = []
    for name, expected_direction, _ in REQUIRED_CONNECTIONS:
        port = ports.get(name)
        if port is None:
            errors.append(f"missing required CPU port {name}")
        elif port.direction != expected_direction:
            errors.append(
                f"CPU port {name} is {port.direction}, expected {expected_direction}"
            )
    if errors:
        raise ValueError("\n".join(errors))


def validate_optional_inputs(ports: dict[str, Port]) -> None:
    required = {item[0] for item in REQUIRED_CONNECTIONS}
    unsupported = [
        name for name, port in ports.items()
        if port.direction in ("input", "inout")
        and name not in required
        and name not in {"clock", "reset"}
    ]
    if unsupported:
        raise ValueError(
            "unsupported optional CPU input ports: " + ", ".join(sorted(unsupported))
        )


def validate_debug_ports(ports: dict[str, Port]) -> None:
    errors = [
        f"CPU debug port {name} is {ports[name].direction}, expected output"
        for name in DEBUG_PORTS
        if name in ports and ports[name].direction != "output"
    ]
    if errors:
        raise ValueError("\n".join(errors))


def render_adapter(ports: dict[str, Port]) -> str:
    validate_required_ports(ports)
    validate_optional_inputs(ports)
    validate_debug_ports(ports)
    connections = [
        f"        .{name:<24}({signal})"
        for name, _, signal in REQUIRED_CONNECTIONS
    ]
    connected = {name for name in DEBUG_PORTS if name in ports}
    connections.extend(
        f"        .{name:<24}({signal})"
        for name, (signal, _) in DEBUG_PORTS.items()
        if name in connected
    )
    required = {item[0] for item in REQUIRED_CONNECTIONS}
    connections.extend(
        f"        .{name:<24}()"
        for name, port in ports.items()
        if port.direction == "output" and name not in required and name not in connected
    )
    declarations = [
        f"    wire {width + ' ' if width else ''}{signal};"
        for name, (signal, width) in DEBUG_PORTS.items()
        if name in connected
    ]
    retire_pc = (
        "retire_pc" if "io_retirePc" in connected
        else "cmt0_pc" if "io_cmt_0_pc" in connected
        else "32'b0"
    )
    rf_wen = (
        "{4{cmt0_valid && cmt0_rd_valid}}"
        if {"io_cmt_0_valid", "io_cmt_0_rd_valid"} <= connected
        else "4'b0"
    )
    rf_wnum = "cmt0_rd" if "io_cmt_0_rd" in connected else "5'b0"
    rf_wdata = "cmt0_data" if "io_cmt_0_data" in connected else "32'b0"
    wb_inst = "cmt0_inst" if "io_cmt_0_inst" in connected else "32'b0"
    return "\n".join(
        (
            ADAPTER_HEADER.rstrip(),
            "",
            "    wire [3:0] cpu_awid;",
            "    wire [7:0] cpu_arlen;",
            "    wire [7:0] cpu_awlen;",
            *declarations,
            "    reg  [3:0] write_id;",
            "",
            "    always @(posedge aclk) begin",
            "        if (!aresetn)",
            "            write_id <= 4'b0;",
            "        else if (awvalid && awready)",
            "            write_id <= cpu_awid;",
            "    end",
            "",
            "    // CPUSTCore emits only single-beat or 16-beat AXI transactions.",
            "    assign arlock  = 2'b00;",
            "    assign arcache = 4'b0000;",
            "    assign arprot  = 3'b000;",
            "    assign awlock  = 2'b00;",
            "    assign awcache = 4'b0000;",
            "    assign awprot  = 3'b000;",
            "    assign awid    = cpu_awid;",
            "    assign wid     = (awvalid && awready) ? cpu_awid : write_id;",
            "    assign arlen   = cpu_arlen[3:0];",
            "    assign awlen   = cpu_awlen[3:0];",
            "    assign ws_valid = 1'b0;",
            "    assign rf_rdata = 32'b0;",
            f"    assign debug0_wb_pc       = {retire_pc};",
            f"    assign debug0_wb_rf_wen   = {rf_wen};",
            f"    assign debug0_wb_rf_wnum  = {rf_wnum};",
            f"    assign debug0_wb_rf_wdata = {rf_wdata};",
            f"    assign debug0_wb_inst     = {wb_inst};",
            "",
            "    CPU u_cpustcore (",
            ",\n".join(connections),
            "    );",
            "",
            "endmodule",
            "",
            "`default_nettype wire",
            "",
        )
    )


def write_if_changed(path: Path, content: str) -> bool:
    if path.exists() and path.read_text(encoding="ascii") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w", encoding="ascii", dir=path.parent, delete=False
    ) as output:
        output.write(content)
        temporary = Path(output.name)
    os.replace(temporary, path)
    return True


def parse_args() -> argparse.Namespace:
    repo_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cpu", type=Path, default=repo_root / "IP/myCPU/CPU.sv")
    parser.add_argument(
        "--output", type=Path, default=repo_root / "IP/myCPU/core_top.sv"
    )
    parser.add_argument(
        "--check", action="store_true", help="fail if the output is not up to date"
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        ports = parse_cpu_ports(args.cpu.read_text(encoding="ascii"))
        generated = render_adapter(ports)
    except (OSError, UnicodeError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    if args.check:
        try:
            existing = args.output.read_text(encoding="ascii")
        except OSError as error:
            print(f"error: {error}", file=sys.stderr)
            return 1
        if existing != generated:
            sys.stdout.writelines(
                difflib.unified_diff(
                    existing.splitlines(keepends=True),
                    generated.splitlines(keepends=True),
                    fromfile=str(args.output),
                    tofile=f"{args.output} (generated)",
                )
            )
            return 1
        print(f"adapter is current: required={len(REQUIRED_CONNECTIONS)} debug=auto")
        return 0

    changed = write_if_changed(args.output, generated)
    print(
        f"{'generated' if changed else 'unchanged'} {args.output}: "
        f"required={len(REQUIRED_CONNECTIONS)} debug=auto"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
